### PR TITLE
Merging master and branch

### PR DESCRIPTION
**Pull request by HawiCaesar**
Need to merge so that I can commit  and push changes from my local copy

### CODE REVIEW

**Comment by JayKay24** [comment]
Amazing. Are those settings in settings.json only limited to vscode? Would love to incorporate that into my code.

**Comment by HawiCaesar** [comment]
Thanks @JayKay24 . I think they are. I am not using them though. They kind of do work.

**Comment by AwuorMarvin** [comment]
It looks really great.

**Comment by JayKay24** [comment]
Oh by the way I would recommend using a.gitignore file to avoid pushing .pyc code to the repo. Just create one and add a line __pycache__/* and git will ignore these files.

**Comment by JayKay24** [comment]
add underscores around pycache. Seems I forgot to add them

**Pull request merged**
